//! The chain, streamed to consumers over gRPC: history from the block archive, then the live
//! chain from the unsafe store, each block with its status, and reorgs and status changes as
//! their own messages. See `docs/stream.md`.
//!
//! ```text
//! UnsafeStore events ─┐
//! ArchiveStore heads ─┴─▶ follower ─▶ window of events ─┐
//!                                                       ├─▶ subscriptions ─▶ gRPC
//! ArchiveStore, UnsafeStore (history, per subscription) ┘
//! ```
//!
//! Next to it, on the same listener, an Arrow Flight service serves ranges of history as
//! columnar record batches (`flight`).
//!
//! [`StreamServer`] is the component; it only reads the stores.

mod convert;
mod flight;
mod follower;
mod service;
mod sink;
mod source;
mod subscription;

use std::net::SocketAddr;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::Duration;

use op_indexer_storage::{ArchiveStore, UnsafeStore};
use tokio::sync::{OwnedSemaphorePermit, Semaphore};
use tokio_util::sync::CancellationToken;
use tokio_util::task::TaskTracker;
use tracing::info;

use crate::flight::Flight;
use crate::follower::{Follower, Live};
use crate::service::Service;
use crate::source::Source;
pub use op_indexer_api::ApiKeys;

/// How long open connections and tasks get to end after shutdown begins.
const SHUTDOWN_GRACE: Duration = Duration::from_secs(5);
/// How often an idle connection is pinged, and how long the answer may take.
const KEEPALIVE_INTERVAL: Duration = Duration::from_secs(30);
const KEEPALIVE_TIMEOUT: Duration = Duration::from_secs(10);
/// The largest message the server sends: a decoded block of a full OP Stack block fits.
/// Clients must accept messages this large (gRPC clients default to 4 MiB).
const MAX_MESSAGE_BYTES: usize = 64 * 1024 * 1024;
/// `GetHeads` and `GetBlock` calls served at once; one more is refused.
const MAX_LOOKUPS: usize = 16;

/// The generated protobuf messages and service of package `opindexer.v1`.
#[expect(
    missing_docs,
    unused_qualifications,
    clippy::allow_attributes,
    clippy::allow_attributes_without_reason,
    clippy::default_trait_access,
    clippy::doc_markdown,
    clippy::large_enum_variant,
    clippy::too_many_lines,
    reason = "generated by tonic-prost-build from proto/opindexer/v1/stream.proto"
)]
pub mod proto {
    tonic::include_proto!("opindexer.v1");
}

/// Flight tickets and descriptors, as the servers read them: for a client of several servers
/// (the balancer) to hand out tickets any server serves.
pub mod ticket {
    pub use op_indexer_api::ticket::{Cap, MAX_FLIGHT_BLOCKS, Query, Table};
}

/// Where the server listens and its limits.
#[derive(Debug, Clone)]
pub struct StreamConfig {
    /// gRPC listen address.
    pub listen_addr: SocketAddr,
    /// Most subscriptions at once; one more is refused.
    pub max_subscriptions: usize,
    /// Most Arrow Flight `DoGet` streams at once; one more waits up to
    /// [`Self::flight_queue`] for a place, then is refused.
    pub max_flights: usize,
    /// How long a `DoGet` waits for a place when [`Self::max_flights`] are taken, among at
    /// most that many waiters; zero refuses at once.
    pub flight_queue: Duration,
    /// The chain's block time: how long the follower waits to read again after a store
    /// failed.
    pub block_time: Duration,
    /// Whether receipts are fetched (the execution network is enabled): without it, blocks
    /// never get receipts. Told to consumers in `Heads`.
    pub receipts: bool,
    /// Whether range sync is on: it fills the archive from its tip up, so heights missing
    /// between the archive and the unsafe store are waited for, not refused.
    pub sync: bool,
    /// API keys a request must carry as `authorization: Bearer <key>`, on the stream and
    /// Flight alike; empty: no check (a local, single-user node).
    pub api_keys: Vec<String>,
}

/// Why the server stopped.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum StreamError {
    /// The gRPC server could not listen, or failed.
    #[error("stream server on {addr} failed")]
    Serve {
        /// The listen address.
        addr: SocketAddr,
        /// The transport's error.
        #[source]
        source: tonic::transport::Error,
    },
}

/// The stream: the gRPC server and the follower behind it.
#[derive(Debug)]
pub struct StreamServer<U, A> {
    config: StreamConfig,
    unsafe_store: U,
    archive: A,
    load: Load,
}

/// How busy the server is, for a balancer: the requests holding one of its places, and the
/// bytes it has sent.
#[derive(Debug, Clone)]
pub struct Load {
    subscriptions: Places,
    flights: Places,
    lookups: Places,
    sent: Sent,
}

/// How many of one limit's places are taken, of how many.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Slots {
    /// Places taken now, and requests waiting for one (so above `max` while some wait).
    pub in_use: usize,
    /// Places in all: the configured limit.
    pub max: usize,
}

/// The bytes of the responses sent to clients so far, counted where each one leaves: one
/// atomic add per message, shared by every clone.
#[derive(Debug, Clone, Default)]
pub(crate) struct Sent(Arc<AtomicU64>);

impl Sent {
    /// Counts `message`, as encoded for the wire.
    pub(crate) fn message(&self, message: &impl prost::Message) {
        let bytes = u64::try_from(message.encoded_len()).unwrap_or(u64::MAX);
        self.0.fetch_add(bytes, Ordering::Relaxed);
    }

    /// The bytes counted so far.
    fn total(&self) -> u64 {
        self.0.load(Ordering::Relaxed)
    }
}

/// One limit: its places, how many there are, and the requests waiting for one (at most as
/// many as there are places).
#[derive(Debug, Clone)]
pub(crate) struct Places {
    free: Arc<Semaphore>,
    waiters: Arc<Semaphore>,
    size: usize,
}

impl Places {
    fn new(size: usize) -> Self {
        let size = size.min(Semaphore::MAX_PERMITS);
        Self {
            free: Arc::new(Semaphore::new(size)),
            waiters: Arc::new(Semaphore::new(size)),
            size,
        }
    }

    /// A place now, if one is free.
    pub(crate) fn try_place(&self) -> Option<OwnedSemaphorePermit> {
        Arc::clone(&self.free).try_acquire_owned().ok()
    }

    /// A place: at once if one is free, else after waiting up to `wait` for one, among at most
    /// as many waiters as places; `None` if none frees in time or the waiters are full.
    pub(crate) async fn place_within(&self, wait: Duration) -> Option<OwnedSemaphorePermit> {
        if let Some(place) = self.try_place() {
            return Some(place);
        }
        if wait.is_zero() {
            return None;
        }
        let _waiting = Arc::clone(&self.waiters).try_acquire_owned().ok()?;
        tokio::time::timeout(wait, Arc::clone(&self.free).acquire_owned())
            .await
            .ok()?
            .ok()
    }

    fn taken(&self) -> usize {
        self.size.saturating_sub(self.free.available_permits())
    }

    /// Places taken, and the requests waiting for one: a pool with waiters is full.
    fn slots(&self) -> Slots {
        let waiting = self.size.saturating_sub(self.waiters.available_permits());
        Slots {
            in_use: self.taken().saturating_add(waiting),
            max: self.size,
        }
    }
}

impl Load {
    fn new(config: &StreamConfig) -> Self {
        Self {
            subscriptions: Places::new(config.max_subscriptions),
            flights: Places::new(config.max_flights),
            lookups: Places::new(MAX_LOOKUPS),
            sent: Sent::default(),
        }
    }

    /// Flight `DoGet` streams being served, of the most allowed at once.
    #[must_use]
    pub fn flights(&self) -> Slots {
        self.flights.slots()
    }

    /// Subscriptions being served, of the most allowed at once.
    #[must_use]
    pub fn subscriptions(&self) -> Slots {
        self.subscriptions.slots()
    }

    /// The bytes of the responses sent to clients since the server started: subscription
    /// events, lookups and Flight data, as encoded for the wire (before compression and
    /// framing). It only grows; a rate is its change over time.
    #[must_use]
    pub fn bytes_sent(&self) -> u64 {
        self.sent.total()
    }

    /// Subscriptions, Flight streams and block lookups being served now.
    #[must_use]
    pub fn in_flight(&self) -> u32 {
        let taken = self
            .subscriptions
            .taken()
            .saturating_add(self.flights.taken())
            .saturating_add(self.lookups.taken());
        u32::try_from(taken).unwrap_or(u32::MAX)
    }
}

impl<U, A> StreamServer<U, A>
where
    U: UnsafeStore + Clone + Send + Sync + 'static,
    A: ArchiveStore,
{
    /// A server reading `unsafe_store` (its blocks and its event stream) and `archive`.
    pub fn new(config: StreamConfig, unsafe_store: U, archive: A) -> Self {
        let load = Load::new(&config);
        Self {
            config,
            unsafe_store,
            archive,
            load,
        }
    }

    /// The server's load, which stays current while it runs.
    #[must_use]
    pub fn load(&self) -> Load {
        self.load.clone()
    }

    /// Serves until `cancel` fires, then ends every subscription and Flight stream (each with
    /// `UNAVAILABLE`) and waits for them and for open connections, at most a few seconds
    /// each.
    ///
    /// # Errors
    ///
    /// Returns [`StreamError::Serve`] if the server cannot listen on its address or fails.
    pub async fn run(self, cancel: CancellationToken) -> Result<(), StreamError> {
        let Self {
            config,
            unsafe_store,
            archive,
            load,
        } = self;
        let source = Source {
            unsafe_store,
            archive,
            cancel: cancel.clone(),
            fills_gaps: config.sync,
        };
        let live = Live::new();
        let follower = Follower {
            source: source.clone(),
            live: Arc::clone(&live),
            retry_after: config.block_time,
            receipts: config.receipts,
        };
        let tasks = TaskTracker::new();
        tasks.spawn(follower.run(cancel.child_token()));
        let flight = Flight {
            source: source.clone(),
            streams: load.flights.clone(),
            queue: config.flight_queue,
            builds: Arc::new(Semaphore::new(flight::max_builds())),
            tasks: tasks.clone(),
            sent: load.sent.clone(),
        };
        let service = Service {
            source,
            live,
            subscriptions: Arc::clone(&load.subscriptions.free),
            lookups: Arc::clone(&load.lookups.free),
            sent: load.sent.clone(),
            tasks: tasks.clone(),
            cancel: cancel.clone(),
            receipts: config.receipts,
        };
        let addr = config.listen_addr;
        info!(
            %addr,
            max_subscriptions = config.max_subscriptions,
            max_flights = config.max_flights,
            "stream server listening"
        );
        let keys = ApiKeys::new(&config.api_keys);
        let stream = proto::stream_server::StreamServer::new(service)
            .max_encoding_message_size(MAX_MESSAGE_BYTES);
        let stream = tonic::service::interceptor::InterceptedService::new(stream, {
            let keys = keys.clone();
            move |request| keys.check(request)
        });
        let flight = arrow_flight::flight_service_server::FlightServiceServer::with_interceptor(
            flight,
            move |request| keys.check(request),
        );
        let serving = tonic::transport::Server::builder()
            // Finds connections whose peer is gone without closing them.
            .http2_keepalive_interval(Some(KEEPALIVE_INTERVAL))
            .http2_keepalive_timeout(Some(KEEPALIVE_TIMEOUT))
            .add_service(stream)
            .add_service(flight)
            .serve_with_shutdown(addr, cancel.cancelled());
        // A graceful stop waits for open connections, and a consumer that stops reading would
        // hold it forever: after the grace period the server stops waiting, and connections
        // still open end with the process.
        let served = tokio::select! {
            served = serving => served,
            () = async {
                cancel.cancelled().await;
                tokio::time::sleep(SHUTDOWN_GRACE).await;
            } => Ok(()),
        };
        // Subscriptions, Flight streams and the follower end on the same token.
        cancel.cancel();
        tasks.close();
        if tokio::time::timeout(SHUTDOWN_GRACE, tasks.wait())
            .await
            .is_err()
        {
            tracing::warn!("stream tasks still running after the grace period; leaving them");
        }
        served.map_err(|source| StreamError::Serve { addr, source })
    }
}
