//! The chain, streamed to consumers over gRPC: history from the block archive, then the live
//! chain from the unsafe store, each block with its status, and reorgs and status changes as
//! their own messages. See `docs/stream.md`.
//!
//! ```text
//! UnsafeStore events ─┐
//! ArchiveStore heads ─┴─▶ follower ─▶ window of events ─┐
//!                                                       ├─▶ subscriptions ─▶ gRPC
//! ArchiveStore, UnsafeStore (history, per subscription) ┘
//! ```
//!
//! Next to it, on the same listener, an Arrow Flight service serves ranges of history as
//! columnar record batches (`flight`).
//!
//! [`StreamServer`] is the component; it only reads the stores.

mod convert;
mod flight;
mod follower;
mod service;
mod source;
mod subscription;

use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use op_indexer_storage::{ArchiveStore, UnsafeStore};
use tokio::sync::Semaphore;
use tokio_util::sync::CancellationToken;
use tokio_util::task::TaskTracker;
use tracing::info;

use crate::flight::Flight;
use crate::follower::{Follower, Live};
use crate::service::Service;
use crate::source::Source;

/// The generated protobuf messages and service of package `opindexer.v1`.
#[expect(
    missing_docs,
    unused_qualifications,
    clippy::allow_attributes,
    clippy::allow_attributes_without_reason,
    clippy::default_trait_access,
    clippy::doc_markdown,
    clippy::large_enum_variant,
    clippy::too_many_lines,
    reason = "generated by tonic-prost-build from proto/opindexer/v1/stream.proto"
)]
pub mod proto {
    tonic::include_proto!("opindexer.v1");
}

/// Where the server listens and its limits.
#[derive(Debug, Clone)]
pub struct StreamConfig {
    /// gRPC listen address.
    pub listen_addr: SocketAddr,
    /// Most subscriptions at once; one more is refused.
    pub max_subscriptions: usize,
    /// Most Arrow Flight `DoGet` streams at once; one more is refused.
    pub max_flights: usize,
    /// The chain's block time: how long the follower waits to read again after a store
    /// failed.
    pub block_time: Duration,
    /// Whether receipts are fetched (the execution network is enabled): without it, blocks
    /// never get receipts. Told to consumers in `Heads`.
    pub receipts: bool,
}

/// Why the server stopped.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum StreamError {
    /// The gRPC server could not listen, or failed.
    #[error("stream server on {addr} failed")]
    Serve {
        /// The listen address.
        addr: SocketAddr,
        /// The transport's error.
        #[source]
        source: tonic::transport::Error,
    },
}

/// The stream: the gRPC server and the follower behind it.
#[derive(Debug)]
pub struct StreamServer<U, A> {
    config: StreamConfig,
    unsafe_store: U,
    archive: A,
}

impl<U, A> StreamServer<U, A>
where
    U: UnsafeStore + Clone + Send + Sync + 'static,
    A: ArchiveStore + Clone + Send + Sync + 'static,
{
    /// A server reading `unsafe_store` (its blocks and its event stream) and `archive`.
    pub const fn new(config: StreamConfig, unsafe_store: U, archive: A) -> Self {
        Self {
            config,
            unsafe_store,
            archive,
        }
    }

    /// Serves until `cancel` fires, then ends every subscription and waits for them.
    ///
    /// # Errors
    ///
    /// Returns [`StreamError::Serve`] if the server cannot listen on its address or fails.
    pub async fn run(self, cancel: CancellationToken) -> Result<(), StreamError> {
        let Self {
            config,
            unsafe_store,
            archive,
        } = self;
        let source = Source {
            unsafe_store,
            archive,
            cancel: cancel.clone(),
        };
        let live = Live::new();
        let follower = Follower {
            source: source.clone(),
            live: Arc::clone(&live),
            retry_after: config.block_time,
        };
        let tasks = TaskTracker::new();
        tasks.spawn(follower.run(cancel.child_token()));
        let flight = Flight {
            source: source.clone(),
            streams: Arc::new(Semaphore::new(config.max_flights)),
            tasks: tasks.clone(),
        };
        let service = Service {
            source,
            live,
            subscriptions: Arc::new(Semaphore::new(config.max_subscriptions)),
            tasks: tasks.clone(),
            cancel: cancel.clone(),
            receipts: config.receipts,
        };
        let addr = config.listen_addr;
        info!(
            %addr,
            max_subscriptions = config.max_subscriptions,
            max_flights = config.max_flights,
            "stream server listening"
        );
        let served = tonic::transport::Server::builder()
            .add_service(proto::stream_server::StreamServer::new(service))
            .add_service(arrow_flight::flight_service_server::FlightServiceServer::new(flight))
            .serve_with_shutdown(addr, cancel.cancelled())
            .await;
        // Subscriptions and the follower end on the same token.
        cancel.cancel();
        tasks.close();
        tasks.wait().await;
        served.map_err(|source| StreamError::Serve { addr, source })
    }
}
