//! The chain, streamed to consumers over gRPC: history from the block archive, then the live
//! chain from the unsafe store, each block with its status, and reorgs and status changes as
//! their own messages. See `docs/stream.md`.
//!
//! ```text
//! UnsafeStore events ─┐
//! ArchiveStore heads ─┴─▶ follower ─▶ window of events ─┐
//!                                                       ├─▶ subscriptions ─▶ gRPC
//! ArchiveStore, UnsafeStore (history, per subscription) ┘
//! ```
//!
//! Next to it, on the same listener, an Arrow Flight service serves ranges of history as
//! columnar record batches (`flight`).
//!
//! [`StreamServer`] is the component; it only reads the stores.

mod auth;
mod convert;
mod flight;
mod follower;
mod service;
mod sink;
mod source;
mod subscription;

use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use op_indexer_storage::{ArchiveStore, UnsafeStore};
use tokio::sync::Semaphore;
use tokio_util::sync::CancellationToken;
use tokio_util::task::TaskTracker;
use tracing::info;

use crate::flight::Flight;
use crate::follower::{Follower, Live};
use crate::service::Service;
use crate::source::Source;

/// How long open connections and tasks get to end after shutdown begins.
const SHUTDOWN_GRACE: Duration = Duration::from_secs(5);
/// How often an idle connection is pinged, and how long the answer may take.
const KEEPALIVE_INTERVAL: Duration = Duration::from_secs(30);
const KEEPALIVE_TIMEOUT: Duration = Duration::from_secs(10);
/// The largest message the server sends: a decoded block of a full OP Stack block fits.
/// Clients must accept messages this large (gRPC clients default to 4 MiB).
const MAX_MESSAGE_BYTES: usize = 64 * 1024 * 1024;
/// `GetHeads` and `GetBlock` calls served at once; one more is refused.
const MAX_LOOKUPS: usize = 16;

/// The generated protobuf messages and service of package `opindexer.v1`.
#[expect(
    missing_docs,
    unused_qualifications,
    clippy::allow_attributes,
    clippy::allow_attributes_without_reason,
    clippy::default_trait_access,
    clippy::doc_markdown,
    clippy::large_enum_variant,
    clippy::too_many_lines,
    reason = "generated by tonic-prost-build from proto/opindexer/v1/stream.proto"
)]
pub mod proto {
    tonic::include_proto!("opindexer.v1");
}

/// Where the server listens and its limits.
#[derive(Debug, Clone)]
pub struct StreamConfig {
    /// gRPC listen address.
    pub listen_addr: SocketAddr,
    /// Most subscriptions at once; one more is refused.
    pub max_subscriptions: usize,
    /// Most Arrow Flight `DoGet` streams at once; one more is refused.
    pub max_flights: usize,
    /// The chain's block time: how long the follower waits to read again after a store
    /// failed.
    pub block_time: Duration,
    /// Whether receipts are fetched (the execution network is enabled): without it, blocks
    /// never get receipts. Told to consumers in `Heads`.
    pub receipts: bool,
    /// Whether range sync is on: it fills the archive from its tip up, so heights missing
    /// between the archive and the unsafe store are waited for, not refused.
    pub sync: bool,
    /// API keys a request must carry as `authorization: Bearer <key>`, on the stream and
    /// Flight alike; empty: no check (a local, single-user node).
    pub api_keys: Vec<String>,
}

/// Why the server stopped.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum StreamError {
    /// The gRPC server could not listen, or failed.
    #[error("stream server on {addr} failed")]
    Serve {
        /// The listen address.
        addr: SocketAddr,
        /// The transport's error.
        #[source]
        source: tonic::transport::Error,
    },
}

/// The stream: the gRPC server and the follower behind it.
#[derive(Debug)]
pub struct StreamServer<U, A> {
    config: StreamConfig,
    unsafe_store: U,
    archive: A,
}

impl<U, A> StreamServer<U, A>
where
    U: UnsafeStore + Clone + Send + Sync + 'static,
    A: ArchiveStore + Clone + Send + Sync + 'static,
{
    /// A server reading `unsafe_store` (its blocks and its event stream) and `archive`.
    pub const fn new(config: StreamConfig, unsafe_store: U, archive: A) -> Self {
        Self {
            config,
            unsafe_store,
            archive,
        }
    }

    /// Serves until `cancel` fires, then ends every subscription and Flight stream (each with
    /// `UNAVAILABLE`) and waits for them and for open connections, at most a few seconds
    /// each.
    ///
    /// # Errors
    ///
    /// Returns [`StreamError::Serve`] if the server cannot listen on its address or fails.
    pub async fn run(self, cancel: CancellationToken) -> Result<(), StreamError> {
        let Self {
            config,
            unsafe_store,
            archive,
        } = self;
        let source = Source {
            unsafe_store,
            archive,
            cancel: cancel.clone(),
            fills_gaps: config.sync,
        };
        let live = Live::new();
        let follower = Follower {
            source: source.clone(),
            live: Arc::clone(&live),
            retry_after: config.block_time,
            receipts: config.receipts,
        };
        let tasks = TaskTracker::new();
        tasks.spawn(follower.run(cancel.child_token()));
        let permits = |limit: usize| Arc::new(Semaphore::new(limit.min(Semaphore::MAX_PERMITS)));
        let flight = Flight {
            source: source.clone(),
            streams: permits(config.max_flights),
            tasks: tasks.clone(),
        };
        let service = Service {
            source,
            live,
            subscriptions: permits(config.max_subscriptions),
            lookups: permits(MAX_LOOKUPS),
            tasks: tasks.clone(),
            cancel: cancel.clone(),
            receipts: config.receipts,
        };
        let addr = config.listen_addr;
        info!(
            %addr,
            max_subscriptions = config.max_subscriptions,
            max_flights = config.max_flights,
            "stream server listening"
        );
        let keys = auth::ApiKeys::new(&config.api_keys);
        let stream = proto::stream_server::StreamServer::new(service)
            .max_encoding_message_size(MAX_MESSAGE_BYTES);
        let stream = tonic::service::interceptor::InterceptedService::new(stream, {
            let keys = keys.clone();
            move |request| keys.check(request)
        });
        let flight = arrow_flight::flight_service_server::FlightServiceServer::with_interceptor(
            flight,
            move |request| keys.check(request),
        );
        let serving = tonic::transport::Server::builder()
            // Finds connections whose peer is gone without closing them.
            .http2_keepalive_interval(Some(KEEPALIVE_INTERVAL))
            .http2_keepalive_timeout(Some(KEEPALIVE_TIMEOUT))
            .add_service(stream)
            .add_service(flight)
            .serve_with_shutdown(addr, cancel.cancelled());
        // A graceful stop waits for open connections, and a consumer that stops reading would
        // hold it forever: after the grace period the server stops waiting, and connections
        // still open end with the process.
        let served = tokio::select! {
            served = serving => served,
            () = async {
                cancel.cancelled().await;
                tokio::time::sleep(SHUTDOWN_GRACE).await;
            } => Ok(()),
        };
        // Subscriptions, Flight streams and the follower end on the same token.
        cancel.cancel();
        tasks.close();
        if tokio::time::timeout(SHUTDOWN_GRACE, tasks.wait())
            .await
            .is_err()
        {
            tracing::warn!("stream tasks still running after the grace period; leaving them");
        }
        served.map_err(|source| StreamError::Serve { addr, source })
    }
}
