[package]
name = "op-indexer-pipeline"
description = "Indexing pipeline: writes unsafe blocks to the unsafe store and promotes them to the committed store once safe"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
op-indexer-primitives.workspace = true
op-indexer-storage.workspace = true

[lints]
workspace = true
