//! The balancer: the directory of a deployment's servers for one chain (`docs/serving.md`
//! section 6). No block data passes through it: it tells clients which servers to read from,
//! and they read from the servers directly.
//!
//! ```text
//! servers ─Register (heartbeats)─▶ table ─┐
//! R2 manifest (every 30 s) ───────────────┼─▶ Flight GetFlightInfo, ListFlights: per-chunk jobs
//!                                         └─▶ Locate: servers for a subscription
//! ```
//!
//! - `table`: the servers registered now, with their heads and load, from their heartbeats.
//!   A server is in it while its `Register` call is open and its heartbeats arrive.
//! - `service`: the gRPC service, `Register` (server key) and `Locate` (user key).
//! - `flight`: Arrow Flight's `GetFlightInfo` and `ListFlights` (user key): a range cut into
//!   one endpoint per sealed chunk, each naming servers by load, and the part above the last
//!   sealed chunk naming the servers whose head covers it with no hole below it.
//! - [`register`]: the server's side, the client that keeps a server registered.
//!
//! [`Balancer`] is the component.

mod flight;
pub mod register;
mod service;
mod table;

use std::fmt;
use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use op_indexer_chainspec::ChainSpec;
use op_indexer_chunks::{ChunkEntry, ChunkStore, Manifest};
use op_indexer_stream::ApiKeys;
use tokio::sync::watch;
use tokio::time::MissedTickBehavior;
use tokio_util::sync::CancellationToken;
use tokio_util::task::TaskTracker;
use tracing::{info, warn};

use crate::flight::Flight;
use crate::service::Service;
use crate::table::Table;

/// How often the manifest is read again for new chunks.
const MANIFEST_REFRESH: Duration = Duration::from_secs(30);
/// How often each server's status is logged.
const STATUS_INTERVAL: Duration = Duration::from_secs(30);
/// Blocks a server may hold behind the newest head before its status is a warning: about
/// a minute of blocks at 1 to 2 s each.
const BEHIND_WARN: u64 = 64;
/// How long a server may have no consensus peer or no execution session before its status is
/// a warning: gossip, or receipts and gap fill, have stalled by then.
const NO_PEERS_WARN: Duration = Duration::from_mins(1);
/// How long open calls and tasks get to end after shutdown begins.
const SHUTDOWN_GRACE: Duration = Duration::from_secs(5);
/// How often an idle connection is pinged, and how long the answer may take: on the
/// balancer's listener and on the servers' registration connection alike.
const KEEPALIVE_INTERVAL: Duration = Duration::from_secs(30);
const KEEPALIVE_TIMEOUT: Duration = Duration::from_secs(10);

/// The generated protobuf messages, server and client of package `opindexer.balancer.v1`.
#[expect(
    missing_docs,
    unused_qualifications,
    clippy::allow_attributes,
    clippy::allow_attributes_without_reason,
    clippy::default_trait_access,
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::too_many_lines,
    reason = "generated by tonic-prost-build from proto/opindexer/balancer/v1/balancer.proto"
)]
pub mod proto {
    tonic::include_proto!("opindexer.balancer.v1");
}

/// Where the balancer listens and whom it lets in.
#[derive(Clone)]
pub struct BalancerConfig {
    /// gRPC listen address, for the balancer service and Flight.
    pub listen_addr: SocketAddr,
    /// Keys users send on `Locate` and Flight, as `authorization: Bearer <key>`: the same keys
    /// the servers accept, since clients then read from them with the same key. Empty: no
    /// check.
    pub api_keys: Vec<String>,
    /// Keys servers send on `Register`. Give at least one: a registration routes users'
    /// traffic, and with none any caller could register.
    pub server_keys: Vec<String>,
}

impl fmt::Debug for BalancerConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // The keys themselves never appear in a log.
        f.debug_struct("BalancerConfig")
            .field("listen_addr", &self.listen_addr)
            .field("api_keys", &self.api_keys.len())
            .field("server_keys", &self.server_keys.len())
            .finish()
    }
}

/// Why the balancer stopped.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum BalancerError {
    /// The gRPC server could not listen, or failed.
    #[error("balancer on {addr} failed")]
    Serve {
        /// The listen address.
        addr: SocketAddr,
        /// The transport's error.
        #[source]
        source: tonic::transport::Error,
    },
}

/// The balancer of one chain.
#[derive(Debug)]
pub struct Balancer {
    config: BalancerConfig,
    chain: &'static ChainSpec,
    store: ChunkStore,
    manifest: Manifest,
}

impl Balancer {
    /// A balancer of `chain`, splitting ranges by the chunks of `manifest`, read from `store`
    /// (read-only: it never writes).
    pub const fn new(
        config: BalancerConfig,
        chain: &'static ChainSpec,
        store: ChunkStore,
        manifest: Manifest,
    ) -> Self {
        Self {
            config,
            chain,
            store,
            manifest,
        }
    }

    /// Serves until `cancel` fires, then ends every registration (`UNAVAILABLE`) and waits
    /// for open calls, at most a few seconds.
    ///
    /// # Errors
    ///
    /// Returns [`BalancerError::Serve`] if the server cannot listen on its address or fails.
    pub async fn run(self, cancel: CancellationToken) -> Result<(), BalancerError> {
        let Self {
            config,
            chain,
            store,
            manifest,
        } = self;
        let (chunks, chunks_rx) = watch::channel(sealed(&manifest));
        let table = Table::default();
        let tasks = TaskTracker::new();
        tasks.spawn(follow_manifest(
            store,
            manifest,
            chunks,
            cancel.child_token(),
        ));
        tasks.spawn(report_servers(table.clone(), cancel.child_token()));
        let users = ApiKeys::new(&config.api_keys);
        let service = Service {
            chain,
            table: table.clone(),
            users: users.clone(),
            servers: ApiKeys::new(&config.server_keys),
            tasks: tasks.clone(),
            cancel: cancel.clone(),
        };
        let flight = Flight {
            table,
            chunks: chunks_rx,
        };
        let addr = config.listen_addr;
        info!(%addr, chain = chain.name, "balancer listening");
        let flight = arrow_flight::flight_service_server::FlightServiceServer::with_interceptor(
            flight,
            move |request| users.check(request),
        );
        let serving = tonic::transport::Server::builder()
            .http2_keepalive_interval(Some(KEEPALIVE_INTERVAL))
            .http2_keepalive_timeout(Some(KEEPALIVE_TIMEOUT))
            .add_service(proto::balancer_server::BalancerServer::new(service))
            .add_service(flight)
            .serve_with_shutdown(addr, cancel.cancelled());
        // Registrations end on the token; a graceful stop then waits for their calls, at most
        // the grace period.
        let served = tokio::select! {
            served = serving => served,
            () = async {
                cancel.cancelled().await;
                tokio::time::sleep(SHUTDOWN_GRACE).await;
            } => Ok(()),
        };
        cancel.cancel();
        tasks.close();
        if tokio::time::timeout(SHUTDOWN_GRACE, tasks.wait())
            .await
            .is_err()
        {
            warn!("balancer tasks still running after the grace period; leaving them");
        }
        served.map_err(|source| BalancerError::Serve { addr, source })
    }
}

/// Logs every [`STATUS_INTERVAL`] one line per registered server: its heads, how far it
/// holds every block, how far that is behind the newest head any server has, its load (bytes
/// per second, Flight streams and subscriptions taken of its limits), and its peers.
/// A server unhealthy, more than [`BEHIND_WARN`] blocks behind, or with no consensus peer or
/// no execution session for more than [`NO_PEERS_WARN`] is logged as a warning.
async fn report_servers(table: Table, cancel: CancellationToken) {
    let mut ticks = tokio::time::interval(STATUS_INTERVAL);
    ticks.set_missed_tick_behavior(MissedTickBehavior::Delay);
    ticks.tick().await;
    loop {
        tokio::select! {
            biased;
            () = cancel.cancelled() => return,
            _ = ticks.tick() => {}
        }
        let servers = table.snapshot();
        let tip = servers
            .iter()
            .filter_map(|(_, server)| server.unsafe_head)
            .max();
        if servers.is_empty() {
            warn!("no server registered");
        }
        for (id, server) in servers {
            let behind = tip
                .zip(server.contiguous_through)
                .map(|(tip, through)| tip.saturating_sub(through));
            let lagging = behind.is_none_or(|behind| behind > BEHIND_WARN);
            let peers = server.peers;
            let slots = server.slots;
            let stalled = server
                .peerless_since
                .is_some_and(|since| since.elapsed() > NO_PEERS_WARN);
            macro_rules! status {
                ($level:ident) => {
                    $level!(
                        server = %id,
                        address = %server.address,
                        healthy = server.healthy,
                        unsafe_head = ?server.unsafe_head,
                        safe = ?server.safe_head,
                        finalized = ?server.finalized_head,
                        contiguous_through = ?server.contiguous_through,
                        behind = ?behind,
                        in_flight = server.requests_in_flight,
                        bytes_per_second = server.bytes_per_second,
                        flights = %Used(slots.flights_in_use, slots.max_flights),
                        subscriptions = %Used(slots.subscriptions_in_use, slots.max_subscriptions),
                        consensus_peers = ?peers.consensus_peers,
                        execution_sessions = ?peers.execution_sessions,
                        execution_inbound = ?peers.execution_inbound,
                        l1_sessions = ?peers.l1_sessions,
                        beacon_peers = ?peers.beacon_peers,
                        "server status"
                    )
                };
            }
            if !server.healthy || lagging || stalled {
                status!(warn);
            } else {
                status!(info);
            }
        }
    }
}

/// Places taken of a limit, as `taken/max`, or `-` when the server does not report them.
struct Used(Option<u32>, Option<u32>);

impl fmt::Display for Used {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match (self.0, self.1) {
            (Some(taken), Some(max)) => write!(f, "{taken}/{max}"),
            _ => f.write_str("-"),
        }
    }
}

/// The sealed chunks of `manifest`, shared with the Flight service.
fn sealed(manifest: &Manifest) -> Arc<[ChunkEntry]> {
    Arc::from(manifest.entries())
}

/// Reads the manifest again every [`MANIFEST_REFRESH`], and publishes the chunks when some
/// were added. A failed read is logged and tried again at the next tick.
async fn follow_manifest(
    store: ChunkStore,
    mut manifest: Manifest,
    chunks: watch::Sender<Arc<[ChunkEntry]>>,
    cancel: CancellationToken,
) {
    let mut ticks = tokio::time::interval(MANIFEST_REFRESH);
    ticks.set_missed_tick_behavior(MissedTickBehavior::Delay);
    ticks.tick().await;
    loop {
        let refreshed = tokio::select! {
            biased;
            () = cancel.cancelled() => return,
            refreshed = async {
                ticks.tick().await;
                manifest.refresh(&store).await
            } => refreshed,
        };
        match refreshed {
            Ok(added) if added.is_empty() => {}
            Ok(added) => {
                info!(
                    added = added.len(),
                    last_block = manifest.last().map(|entry| entry.last),
                    "new sealed chunks in the manifest"
                );
                chunks.send_replace(sealed(&manifest));
            }
            Err(err) => warn!(%err, "failed to read the manifest; trying again later"),
        }
    }
}
