[package]
name = "op-indexer-el"
description = "Execution p2p: devp2p discovery and sessions with OP Stack execution peers, fetching verified receipts"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
op-indexer-chainspec.workspace = true
op-indexer-primitives.workspace = true

alloy-consensus.workspace = true
alloy-eip2124.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
discv5.workspace = true
enr.workspace = true
fastrand.workspace = true
futures-util.workspace = true
libp2p-identity.workspace = true
metrics.workspace = true
op-alloy-consensus.workspace = true
reth-ecies.workspace = true
reth-eth-wire.workspace = true
reth-eth-wire-types.workspace = true
reth-network-peers.workspace = true
secp256k1.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "sync", "time", "rt", "macros"] }
tokio-util.workspace = true
tracing.workspace = true

[lints]
workspace = true
